<a href="https://colab.research.google.com/github/shrutin0492/Deep-Learning-and-Computer-Vision-Lab/blob/main/design_single_layer_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Designing a single layer neural network using various activation functions:**
- *Tanh*
- *ReLU*
- *Leaky ReLU*
- *Sigmoid*

# Tanh

In [10]:
from numpy import exp, array, random, dot, tanh

class NeuralNetwork():
    def __init__(self):
        random.seed(1)
        self.weight_matrix = 2 * random.random((3, 1)) - 1

    def tanh(self, x):
        return tanh(x)

    def tanh_derivative(self, x):
        return 1.0 - tanh(x)**2

    def forward_propagation(self, inputs):
        return self.tanh(dot(inputs, self.weight_matrix))

    def train(self, train_inputs, train_outputs, num_train_iterations):
        for iteration in range(num_train_iterations):
            output = self.forward_propagation(train_inputs)
            error = train_outputs - output
            adjustment = dot(train_inputs.T, error * self.tanh_derivative(output))
            self.weight_matrix += adjustment

if __name__ == '__main__':
    neural_network = NeuralNetwork()
    print('Random weights at the start of training')
    print(neural_network.weight_matrix)
    train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    train_outputs = array([[0, 1, 1, 0]]).T
    neural_network.train(train_inputs, train_ou–tputs, 10000)
    print('New weights after training')
    print(neural_network.weight_matrix)
    print("Testing network on new examples->")
    print(neural_network.forward_propagation(array([1, 0, 0])))


Random weights at the start of training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New weights after training
[[5.39428067]
 [0.19482422]
 [0.34317086]]
Testing network on new examples->
[0.99995873]


# ReLU

In [21]:
from numpy import array, random, dot

class NeuralNetwork():
    def __init__(self):
        random.seed(1)
        # He initialization for weights
        self.weight_matrix = random.randn(3, 1) * (2 / 3)  # 2/3 is the fan-in for this layer

    def relu(self, x):
        # ReLU activation function
        return x * (x > 0)

    def relu_derivative(self, x):
        # Derivative of ReLU activation function
        return 1. * (x > 0)

    def forward_propagation(self, inputs):
        # Forward propagation using ReLU activation function
        return self.relu(dot(inputs, self.weight_matrix))

    def train(self, train_inputs, train_outputs, num_train_iterations, learning_rate=0.01):
        # Training the neural network
        for iteration in range(num_train_iterations):
            output = self.forward_propagation(train_inputs)
            error = train_outputs - output
            # Adjusting weights using gradient descent with learning rate
            adjustment = learning_rate * dot(train_inputs.T, error * self.relu_derivative(output))
            self.weight_matrix += adjustment

if __name__ == '__main__':
    neural_network = NeuralNetwork()
    print('Random weights at the start of training')
    print(neural_network.weight_matrix)
    train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    train_outputs = array([[0, 1, 1, 0]]).T
    neural_network.train(train_inputs, train_outputs, 10000, learning_rate=0.1)  # Adjusted learning rate
    print('New weights after training')
    print(neural_network.weight_matrix)
    print("Testing network on new examples->")
    print(neural_network.forward_propagation(array([1, 0, 0])))


Random weights at the start of training
[[ 1.08289691]
 [-0.40783761]
 [-0.3521145 ]]
New weights after training
[[ 1.21750571e+00]
 [-1.01856302e-16]
 [-2.17505705e-01]]
Testing network on new examples->
[1.21750571]


# Leaky ReLU

In [19]:
from numpy import exp, array, random, dot

class NeuralNetwork():
    def __init__(self):
        random.seed(1)
        # Xavier initialization for weights
        self.weight_matrix = random.randn(3, 1) * (2 / 3)  # 2/3 is the fan-in for this layer

    def leaky_relu(self, x):
        # Leaky ReLU activation function
        return x * (x > 0) + 0.01 * x * (x <= 0)  # 0.01 is the slope for negative inputs

    def leaky_relu_derivative(self, x):
        # Derivative of Leaky ReLU activation function
        return 1. * (x > 0) + 0.01 * (x <= 0)  # 0.01 is the slope for negative inputs

    def forward_propagation(self, inputs):
        # Forward propagation using Leaky ReLU activation function
        return self.leaky_relu(dot(inputs, self.weight_matrix))

    def train(self, train_inputs, train_outputs, num_train_iterations):
        # Training the neural network
        for iteration in range(num_train_iterations):
            output = self.forward_propagation(train_inputs)
            error = train_outputs - output
            # Adjusting weights using gradient descent
            adjustment = dot(train_inputs.T, error * self.leaky_relu_derivative(output))
            self.weight_matrix += adjustment

if __name__ == '__main__':
    neural_network = NeuralNetwork()
    print('Random weights at the start of training')
    print(neural_network.weight_matrix)
    train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    train_outputs = array([[0, 1, 1, 0]]).T
    neural_network.train(train_inputs, train_outputs, 10000)
    print('New weights after training')
    print(neural_network.weight_matrix)
    print("Testing network on new examples->")
    print(neural_network.forward_propagation(array([1, 0, 0])))


Random weights at the start of training
[[ 1.08289691]
 [-0.40783761]
 [-0.3521145 ]]
New weights after training
[[ 2.00223261]
 [-0.96519995]
 [-0.00686515]]
Testing network on new examples->
[2.00223261]


# Sigmoid

In [22]:
from numpy import array, random, dot, exp

class NeuralNetwork():
    def __init__(self):
        random.seed(1)
        # Xavier initialization for weights
        self.weight_matrix = random.randn(3, 1) * (2 / 3)  # 2/3 is the fan-in for this layer

    def sigmoid(self, x):
        # Sigmoid activation function
        return 1 / (1 + exp(-x))

    def sigmoid_derivative(self, x):
        # Derivative of sigmoid activation function
        return x * (1 - x)

    def forward_propagation(self, inputs):
        # Forward propagation using sigmoid activation function
        return self.sigmoid(dot(inputs, self.weight_matrix))

    def train(self, train_inputs, train_outputs, num_train_iterations, learning_rate=0.01):
        # Training the neural network
        for iteration in range(num_train_iterations):
            output = self.forward_propagation(train_inputs)
            error = train_outputs - output
            # Adjusting weights using gradient descent with learning rate
            adjustment = learning_rate * dot(train_inputs.T, error * self.sigmoid_derivative(output))
            self.weight_matrix += adjustment

if __name__ == '__main__':
    neural_network = NeuralNetwork()
    print('Random weights at the start of training')
    print(neural_network.weight_matrix)
    train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    train_outputs = array([[0, 1, 1, 0]]).T
    neural_network.train(train_inputs, train_outputs, 10000, learning_rate=0.1)  # Adjusted learning rate
    print('New weights after training')
    print(neural_network.weight_matrix)
    print("Testing network on new examples->")
    print(neural_network.forward_propagation(array([1, 0, 0])))


Random weights at the start of training
[[ 1.08289691]
 [-0.40783761]
 [-0.3521145 ]]
New weights after training
[[ 7.26526317]
 [-0.22329088]
 [-3.41398404]]
Testing network on new examples->
[0.99930107]
